export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const ALL_PRODUCT_RECEIVED = "ALL_PRODUCT_RECEIVED";
export const PRODUCT_ERROR_OCCURED = "PRODUCT_ERROR_OCCURED";

export const GET_SPECIFIC_PRODUCT = "GET_SPECIFIC_PRODUCT";
export const SPECIFIC_PRODUCT_RECEIVED = "SPECIFIC_PRODUCT_RECEIVED";
export const SPECIFIC_PRODUCT_ERROR = "SPECIFIC_PRODUCT_ERROR";
